apiVersion: batch/v1
kind: Job
metadata:
  name: download-model
spec:
  template:
    spec:
      containers:
        - name: downloader
          image: python:3.10
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p "\${MOUNT_PATH}/\${MODEL_PATH}" && \
              pip install huggingface_hub && \
              export PATH="\${PATH}:\${HOME}/.local/bin" && \
              $( if echo "${LLMDBENCH_LLMD_IMAGE_NAME}" | grep -q "sim"; then
                   echo ""
                 else
                   echo "hf auth login --token \"\${HF_TOKEN}\" &&"
                 fi ) \
              hf download "\${HF_MODEL_ID}" --local-dir "/cache/\${MODEL_PATH}"
          env:
            - name: MODEL_PATH
              value: /models/REPLACE_MODEL
            - name: HF_MODEL_ID
              value: REPLACE_MODEL
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
            - name: HF_HOME
              value: /tmp/huggingface
            - name: HOME
              value: /tmp
            - name: MOUNT_PATH
              value: /cache
          volumeMounts:
            - name: model-cache
              mountPath: /cache
      restartPolicy: OnFailure
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-pvc