apiVersion: v1
data:
  large_model_long_input.yaml.in: |-
    model_name: "REPLACE_ENV_LLMDBENCH_DEPLOY_CURRENT_MODEL"
    image: "REPLACE_ENV_LLMDBENCH_HARNESS_CONTAINER_IMAGE"
    service_account: "REPLACE_ENV_LLMDBENCH_HARNESS_SERVICE_ACCOUNT"
    pvc_name: "REPLACE_ENV_LLMDBENCH_HARNESS_PVC_NAME"
    scenarios: "long-input"
    qps_values: "0.1 0.25 0.5 1 2 3 4 5"
    num_users_warmup: 5
    num_users: 3
    num_rounds: 5
    system_prompt: 256
    chat_history: 1024
    answer_len: 32
    init_user_id: 1
    test_duration: 300
    use_chat_completions: true
  medium_model_long_input.yaml.in: |-
    model_name: "REPLACE_ENV_LLMDBENCH_DEPLOY_CURRENT_MODEL"
    image: "REPLACE_ENV_LLMDBENCH_HARNESS_CONTAINER_IMAGE"
    service_account: "REPLACE_ENV_LLMDBENCH_HARNESS_SERVICE_ACCOUNT"
    pvc_name: "REPLACE_ENV_LLMDBENCH_HARNESS_PVC_NAME"
    scenarios: "long-input"
    qps_values: "0.1 0.25 0.5 1 2 3 4 5"
    num_users_warmup: 5
    num_users: 3
    num_rounds: 5
    system_prompt: 512
    chat_history: 2048
    answer_len: 64
    init_user_id: 1
    test_duration: 300
    use_chat_completions: true
  sanity_long-input.yaml.in: |-
    model_name: "REPLACE_ENV_LLMDBENCH_DEPLOY_CURRENT_MODEL"
    image: "REPLACE_ENV_LLMDBENCH_HARNESS_CONTAINER_IMAGE"
    service_account: "REPLACE_ENV_LLMDBENCH_HARNESS_SERVICE_ACCOUNT"
    pvc_name: "REPLACE_ENV_LLMDBENCH_HARNESS_PVC_NAME"
    scenarios: "long-input"
    qps_values: "1.34"
    num_users_warmup: 1
    num_users: 1
    num_rounds: 1
    system_prompt: 256
    chat_history: 1024
    answer_len: 32
    init_user_id: 1
    test_duration: 30
    use_chat_completions: false
  sanity_sharegpt.yaml.in: |-
    model_name: "REPLACE_ENV_LLMDBENCH_DEPLOY_CURRENT_MODEL"
    image: "REPLACE_ENV_LLMDBENCH_HARNESS_CONTAINER_IMAGE"
    service_account: "REPLACE_ENV_LLMDBENCH_HARNESS_SERVICE_ACCOUNT"
    pvc_name: "REPLACE_ENV_LLMDBENCH_HARNESS_PVC_NAME"
    scenarios: "sharegpt"
    qps_values: "1.34"
    num_users_warmup: 1
    num_users: 1
    num_rounds: 1
    system_prompt: 256
    chat_history: 1024
    answer_len: 32
    init_user_id: 1
    test_duration: 30
    use_chat_completions: false
  sanity_short-input.yaml.in: |-
    model_name: "REPLACE_ENV_LLMDBENCH_DEPLOY_CURRENT_MODEL"
    image: "REPLACE_ENV_LLMDBENCH_HARNESS_CONTAINER_IMAGE"
    service_account: "REPLACE_ENV_LLMDBENCH_HARNESS_SERVICE_ACCOUNT"
    pvc_name: "REPLACE_ENV_LLMDBENCH_HARNESS_PVC_NAME"
    scenarios: "short-input"
    qps_values: "0.5"
    num_users_warmup: 1
    num_users: 1
    num_rounds: 1
    system_prompt: 256
    chat_history: 1024
    answer_len: 32
    init_user_id: 1
    test_duration: 30
    use_chat_completions: false
  small_model_long_input.yaml.in: |-
    model_name: "REPLACE_ENV_LLMDBENCH_DEPLOY_CURRENT_MODEL"
    image: "REPLACE_ENV_LLMDBENCH_HARNESS_CONTAINER_IMAGE"
    service_account: "REPLACE_ENV_LLMDBENCH_HARNESS_SERVICE_ACCOUNT"
    pvc_name: "REPLACE_ENV_LLMDBENCH_HARNESS_PVC_NAME"
    scenarios: "long-input"
    qps_values: "0.1 0.25 0.5"
    num_users_warmup: 1
    num_users: 1
    num_rounds: 1
    system_prompt: 256
    chat_history: 1024
    answer_len: 32
    init_user_id: 1
    test_duration: 60
    use_chat_completions: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fmperf-profiles
