apiVersion: v1
data:
  sanity_concurrent.yaml.in: |-
    target: REPLACE_ENV_LLMDBENCH_HARNESS_STACK_ENDPOINT_URL
    rate-type: concurrent
    rate: 2
    max-seconds: 30
    data: prompt_tokens=256,output_tokens=128
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: guidellm-profiles
